### ISSUE TITLE
osm-lump-ways-down fails with index out of bounds error

### ISSUE THREAD

**Issue by Colbertson** [amandasaurus/osm-lump-ways#2]
File was created by opening this shapefile: [Ūdensteču vietvārdi .shp formātā](https://www.lgia.gov.lv/lv/vietvardu-dati-atvertajos-datos) in JOSM using the OpenData plugin, then exporting as a .osm.pbf using the PBF plugin

[VDB_udensteces.zip](https://github.com/user-attachments/files/16090447/VDB_udensteces.zip)

Heres the command and error:
```
colby@colby-desktop:~/Documents/OSM/Udensteces_atv-datiem_2024_06$ ./osm-lump-ways-down --input-filename VDB_udensteces.osm.pbf --output-filename udensteces%s.geojson --upstreams file.geojson
[2024-07-03T20:09:52Z INFO  osm_lump_ways_down] Starting osm-lump-ways-down v1.0.0
[2024-07-03T20:09:52Z INFO  osm_lump_ways_down] Starting to read "VDB_udensteces.osm.pbf"
[2024-07-03T20:09:52Z INFO  osm_lump_ways_down] No tag filtering in operation. All ways in the file will be used.
[2024-07-03T20:09:52Z INFO  osm_lump_ways_down] Reading input file...
[2024-07-03T20:09:52Z INFO  osm_lump_ways_down] Finished reading. 4,842 ways, and 618,413 nodes, read in 0.3sec, 17,524 ways/sec
[2024-07-03T20:09:52Z INFO  osm_lump_ways_down] Latest timestamp is 0 / 1970-01-01T00:00:00Z
[2024-07-03T20:09:52Z INFO  osm_lump_ways_down] All data has been loaded in 0.3sec. Started processing...
[2024-07-03T20:09:52Z INFO  osm_lump_ways_down] Size of the connected graph: 615,839 nodes
[2024-07-03T20:09:52Z INFO  osm_lump_ways_down] Splitting this large graph into many smaller non-connected graphs...
[2024-07-03T20:09:52Z INFO  osm_lump_ways_down] Split the graph into 2,796 different disconnected graphs
[2024-07-03T20:09:53Z INFO  osm_lump_ways_down] Found 13 cycles, comprised of 838 nodes
[00:00:00] 100% done. eta   0s ██████████ 1231678/1231678 20,348,892.6804/s Looking for cycles
[00:00:00] 100% done. eta   0s ██████████    2796/2796    46,211.1089/s Graphs processed            thread '<unnamed>' panicked at /home/colby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/osm-lump-ways-1.0.0/src/bin/../nodeid_position.rs:230:19:
index out of bounds: the len is 64 but the index is 18446744073709551612
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/colby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/osm-lump-ways-1.0.0/src/bin/osm-lump-ways-down.rs:1074:31:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at /home/colby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/osm-lump-ways-1.0.0/src/bin/osm-lump-ways-down.rs:1074:31:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '<unnamed>' panicked at /home/colby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/osm-lump-ways-1.0.0/src/bin/osm-lump-ways-down.rs:1074:31:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
colby@colby-desktop:~/Documents/OSM/Udensteces_atv-datiem_2024_06$ 
```

**Comment by amandasaurus** [comment]
That input file has negative object ids, which is to be expected 

I've [fixed](https://github.com/amandasaurus/osm-lump-ways/commit/11235e1a93309182c7bd92fccfbfb25aea7f1e52) this by correctly showing an error, and updating the [Readme](https://github.com/amandasaurus/osm-lump-ways#:~:text=the%20input%20object%20ids%20must%20be%20positive).

You can make your input file acceptable with `osmium sort` & `osmium renumber`.  (cf. readme).
